version: '3.7'

volumes:
  postgres:

services:
  postgres:
    container_name: postgres
    image: "postgres:12"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/data/postgres"
    volumes:
      - postgres:/var/lib/postgres/data
    ports:
      - "5432:5432"

  task-api:
    container_name: task_api
    image: juniorbmonteiro/task-api
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    depends_on:
      - postgres